version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    container_name: postgresql
    networks:
      - airflow
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1

  redis:
    image: 'bitnami/redis:latest'
    networks:
      - airflow
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  airflow-worker:
    image: rubiklabs/airflow-worker:2.3.0-d1
    container_name: worker
    networks:
      - airflow
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_LOAD_EXAMPLES=yes
      - AIRFLOW_WEBSERVER_HOST=webserver

  airflow-scheduler:
    image: rubiklabs/airflow-scheduler:2.3.0-d1
    container_name: scheduler
    networks:
      - airflow
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_LOAD_EXAMPLES=yes
      - AIRFLOW_WEBSERVER_HOST=webserver

  airflow:
    image: rubiklabs/airflow:2.3.0-d1
    container_name: webserver
    networks:
      - airflow
    environment:
      - AIRFLOW_FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW_SECRET_KEY=a25mQ1FHTUh3MnFRSk5KMEIyVVU2YmN0VGRyYTVXY08=
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_PASSWORD=admin
      - AIRFLOW_USERNAME=admin
      - AIRFLOW_EMAIL=admin@example.com
    ports:
      - '8080:8080'

networks:
  airflow: